// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repository.Models;

public partial class KoiFish
{
    public long KoiFishId { get; set; }

    public string Name { get; set; }

    public long? CategoryId { get; set; }

    public long? SizeId { get; set; }

    public string Description { get; set; }

    public DateTime? Dob { get; set; }

    public double? Price { get; set; }

    public string Origin { get; set; }

    public string Gender { get; set; }

    public byte[]? ImageData { get; set; }

    public string? Type { get; set; }
    public string CreatedBy { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<KoiOrderDetail> KoiOrderDetails { get; set; } = new List<KoiOrderDetail>();

    public virtual Size Size { get; set; }
}