// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repository.Models;

public partial class KoiOrder
{
    public long KoiOrderId { get; set; }

    public long? CustomerId { get; set; }

    public int? Quantity { get; set; }

    public double? Price { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<KoiOrderDetail> KoiOrderDetails { get; set; } = new List<KoiOrderDetail>();
}