// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repository.Models;

public partial class KoiOrderDetail
{
    public long KoiOrderDetailId { get; set; }

    public long? KoiOrderId { get; set; }

    public long? KoiFishId { get; set; }

    public double? TotalPrice { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual KoiFish KoiFish { get; set; }

    public virtual KoiOrder KoiOrder { get; set; }
}